class PROMPT:
    NoToken = "唔……该音卡实例没有填写JX3API的token，数据获取失败，请联系机器人主人！"
    ServerNotExist = "唔……没有找到服务器参数，群聊似乎也没有绑定服务器哦，要不绑定试试呢？"
    ArgumentInvalid = "唔……参数数量有误，请检查后重试~"
    NoTicket = "唔……该音卡实例没有填写推栏的Ticket，数据获取失败，请联系机器人主人！"
    ServerInvalid = "唔……服务器输入有误！"
    ArgumentCountInvalid = "唔……参数数量有误，请检查后重试！"
    NumberInvalid = "唔……输入的不是数字哦，取消搜索。"
    InvalidToken = "唔……该音卡实例的JX3API的token无效，请联系机器人主人！"
    NumberNotExist = "唔……输入的数字不在范围内哦，请检查后重试！"
    PlayerNotExist = "唔……未找到该玩家，请提交角色！\n提交角色 服务器 UID"