version: '3'
services:
  inkar-suki:
    image: registry.cn-hangzhou.aliyuncs.com/hzzz9/inkar-suki:latest
    container_name: inkar-suki
    restart: always
    networks:
      - default
    volumes:
      - ./config/config.yml:/app/src/config/config.yml
      - ./data:/app/src/data
      - ./const/cache:/app/src/const/cache
    ports:
      - 2333:2333

networks:
  default:
    name: inkar
