from .dujing import generate_calculator_img_dujing as dj_calculator
from .wufang import generate_calculator_img_wufang as wf_calculator
from .yinlongjue import generate_calculator_img_yinlongjue as ylj_calculator
from .shanhaixinjue import generate_calculator_img_shanhaixinjue as shxj_calculator
from .zixiagong import get_calculated_img_zixiagong as zxg_calculator